controllers: Add OcsClient and StorageClassClaim controllers
red-hat-storage/ocs-client-operator pull request #1
Opened 2022-08-22 17:33 UTC by jarrpa

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

2022-09-22 04:30 UTC, Madhu-1 requested changes
Few nits and Need to rebase on top of the latest ocs-operator for the claim controller.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +		r.Log.Error(err, "External-OCS:Failed to acknowledge onboarding.")
Do we need to keep `External-OCS` in logging?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	_, err := externalClusterClient.AcknowledgeOnboarding(context.Background(), instance.Status.ConsumerID)
use context from Reconcile

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	// instance.Status.Phase = statusutil.PhaseProgressing
We should update the Phase to connected after successful acknowledment?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	return reconcile.Result{Requeue: true}, nil
After acknowledging the client do we need to requeue?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	_, err := externalClusterClient.OffboardConsumer(context.Background(), instance.Status.ConsumerID)
use context from Reconcile

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +		context.Background(),
use context from Reconcile

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +// getExternalConfigFromProvider makes an API call to the external storage provider cluster for json blob
Remove commented code?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +func (r *OcsClientReconciler) logGrpcErrorAndReportEvent(instance *v1alpha1.OcsClient, grpcCallName string, err error, errCode codes.Code) {
We are not reporting any event from this function. Do we plan to do it in the future?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	err = r.Client.Create(context.TODO(), claim)
use Reconcile context

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +			Labels:    map[string]string{
remove labels if we are not setting anything.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +				//defaultStorageClassClaimLabel: "true",
remove labels if we are not setting anything.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/ocsclient_controller.go
> +	err := r.createAndOwnStorageClassClaim(instance, storageClassClaimFile)
Move this to line 450 so that struct and function will remain next to reach other.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +Copyright 2020 Red Hat, Inc.
2022

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +		Watches(&source.Kind{Type: &storagev1.StorageClass{}}, enqueueStorageConsumerRequest).
also need to watch for snapshotclass changes

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +		r.log.Info("Failed to update StorageClassClaim status.")
log as an error?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +	result, reconcileError = r.reconcileConsumerPhases()
As we dont have both provider and consumer in storageclassclaim anymore rename `reconcileConsumerPhases` to `reconcilePhases`?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +			if !((sccType == "sharedfilesystem" && scIsFSType && !scHasEncryptionMethod) ||
There was a bug with this validation we change the validation, it looks like the reference was taken from pretty old code.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +			storageClassClaimStorageType,
storageProfile is missing

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +					return reconcile.Result{}, fmt.Errorf("failed to create or update secret %v: %s", secret, err)
return just secret name and namespace instead of complete secret struct?

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +				}
volumesnapshot feature is missing.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +				err = r.createOrReplaceStorageClass(storageClass)
When a new cephfs storageclass/snapshot classes are created, we need to update clusterID in the csi configmap. i hope we will take care of it.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +			Namespace: r.storageClassClaim.Namespace,
a namespace is not required for storageclass as it is cluster scoped resources.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +			Name:      r.storageClassClaim.Name,
a namespace is not required for storageclass as it is cluster scoped resources.

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +	}
We should have moved this inside `existing.UID` check as it make sense to have comparison only when storageclass exists

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +		r.log.Info("StorageClass needs to be updated, deleting it.", "StorageClass", klog.KRef(storageClass.Namespace, existing.Name))
no namespace required for storageclass

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +			r.log.Error(err, "Failed to delete StorageClass.", "StorageClass", klog.KRef(storageClass.Namespace, existing.Name))
no namespace required for storageclass

2022-09-22 04:30 UTC, Madhu-1 commented on controllers/storageclassclaim_controller.go
> +	r.log.Info("Creating StorageClass.", "StorageClass", klog.KRef(storageClass.Namespace, existing.Name))
no namespace required for storageclass

2023-01-23 16:04 UTC, jarrpa commented
Closing in favor of #6.

2023-01-23 16:04 UTC, closed without merging