bundle: update csv with info required for release
red-hat-storage/ocs-client-operator pull request #158
Opened 2024-05-27 03:44 UTC by leelavg

CSV description and annotations required for the release are updated

2024-05-27 03:44 UTC, leelavg commented
/hold

for some clarifications on labels & valid-subscription.

2024-05-27 03:44 UTC, leelavg commented
/cherry-pick release-4.16

2024-05-27 05:01 UTC, leelavg commented
/unhold

2024-05-27 16:54 UTC, nb-ohad requested changes

2024-05-27 16:54 UTC, nb-ohad commented on bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
> +    for workloads.
```suggestion
  description: OpenShift Data Foundation client operator enables consumption of storage services from a remote centralized OpenShift Data Foundation provider cluster 
```

2024-05-29 07:22 UTC, leelavg commented on bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
> +    for workloads.
done.

2024-05-29 07:32 UTC, leelavg commented
/hold

for a decision on suggested namespace annotation.

2024-05-29 14:58 UTC, leelavg commented
/unhold

2024-05-29 15:02 UTC, nb-ohad commented
\lgtm

2024-05-29 15:03 UTC, nb-ohad commented
/lgtm

2024-05-29 15:06 UTC, merged