Add a deletion safegaurd mechanism for csi resources
red-hat-storage/ocs-client-operator pull request #81
Opened 2024-02-20 08:15 UTC by bernerhat

Addition to the based upon branch, adding a check to verify there is no PVs created by us prior deletion of the operator in order to prevent a scenario where dormant storage is present with no possible access by the user.

2024-02-22 10:21 UTC, leelavg reviewed
last commit lg

2024-03-04 06:44 UTC, leelavg commented
@bernerhat what's the update on this PR?

2024-03-04 08:59 UTC, bernerhat commented
code still needs to be tested atm.

2024-03-14 11:19 UTC, bernerhat commented
/hold

2024-04-08 04:17 UTC, leelavg commented on controllers/operatorconfigmap_controller.go
> +func (c *OperatorConfigMapReconciler) verifyNoStorageClassClaimsExist() (bool, error) {
StorageClassClaims API is deprecated in favour of StorageClaims, pls recheck.

2024-04-08 04:17 UTC, leelavg commented on controllers/operatorconfigmap_controller.go
> +	err := c.Client.List(c.ctx, storageClassClaims)
is there no `c.list` method?

2024-04-08 04:17 UTC, leelavg commented on controllers/operatorconfigmap_controller.go
> +	err := c.Client.List(c.ctx, storageClassClaims)
you only need to know the presence, check using a limit, `client.Limit(1)`

2024-04-08 04:17 UTC, leelavg commented on controllers/operatorconfigmap_controller.go
> +	if claimsPresent {
```suggestion
	} else if claimsPresent {
```

2024-04-08 04:17 UTC, leelavg commented on controllers/operatorconfigmap_controller.go
> +		return ctrl.Result{Requeue: true, RequeueAfter: 10 * time.Second}, nil
let's converge on sending an error only rather than requeue as this is a user operation which can't be timed.

2024-04-16 09:45 UTC, nb-ohad requested changes

2024-04-16 09:45 UTC, nb-ohad commented on controllers/operatorconfigmap_controller.go
> +		c.log.Error(err, "unable to verify StorageClaims presence prior to deletion of ceph resources")
```suggestion
		c.log.Error(err, "unable to verify StorageClaims presence prior to removal of CSI resources")
```

2024-04-16 09:45 UTC, nb-ohad commented on controllers/operatorconfigmap_controller.go
> +		c.log.Error(err, "Waiting for all storageClaims to be deleted.")
```suggestion
		err = fmt.Errorf("failed to clean up resources: storage claims are present on the cluster")
```

2024-04-16 10:20 UTC, nb-ohad commented
/lgtm

2024-04-16 10:21 UTC, nb-ohad commented
/unhold

2024-04-16 10:23 UTC, merged